// @flow
/* eslint no-underscore-dangle: 0 */
/* eslint no-mixed-operators: 0 */

export const CHECKOUT_OPENED_MODAL = 'CHECKOUT_OPENED_MODAL'
export const CHECKOUT_USER_CLOSED_MODAL = 'CHECKOUT_USER_CLOSED_MODAL'
export const VOUCHER_VALIDATE = 'VOUCHER_VALIDATE'
export const CHECKOUT_EMAIL_FOCUSED = 'CHECKOUT_EMAIL_FOCUSED'
export const CHECKOUT_CHARDHOLDERNAME_FOCUSED =
  'CHECKOUT_CHARDHOLDERNAME_FOCUSED'
export const CHECKOUT_COMPANYNAME_FOCUSED = 'CHECKOUT_COMPANYNAME_FOCUSED'
export const CHECKOUT_VATNUMBER_FOCUSED = 'CHECKOUT_VATNUMBER_FOCUSED'
export const CHECKOUT_CARDNUMBER_FOCUSED = 'CHECKOUT_CARDNUMBER_FOCUSED'
export const CHECKOUT_EXPIRATIONDATE_FOCUSED = 'CHECKOUT_EXPIRATIONDATE_FOCUSED'
export const CHECKOUT_CVC_FOCUSED = 'CHECKOUT_CVC_FOCUSED'
export const CHECKOUT_PAYMENT_VALIDATE_ERROR = 'CHECKOUT_PAYMENT_VALIDATE_ERROR'
export const CHECKOUT_PAYMENT_REQUEST = 'CHECKOUT_PAYMENT_REQUEST'
export const CHECKOUT_PAYMENT_SUCCESS = 'CHECKOUT_PAYMENT_SUCCESS'
export const CHECKOUT_PAYMENT_ERROR_STRIPE = 'CHECKOUT_PAYMENT_ERROR_STRIPE'
export const CHECKOUT_PAYMENT_ERROR_API = 'CHECKOUT_PAYMENT_ERROR_API'
