export const HOME_PAGE = 'homepage'
export const BOOTCAMP = 'bootcamp'
export const COMMUNITY = 'community'
export const CORP_TRAINING = 'corpTraining'
export const CURRICULUM = 'curriculum'
export const LONDON_BOOTCAMP = 'londonBootcamp'
