describe('programmatically generated pages', function () {
  it('renders with the correct info', function () {
    cy.visit('/react-redux-training-paris/')
    cy.get('h2').contains('Paris - France')
    cy.visit('/react-redux-training-sydney/')
    cy.get('h2').contains('Sydney - Australia')
    cy.visit('/react-redux-training-brussels/')
    cy.get('h2').contains('Brussels - Belgium')
    cy.visit('/react-redux-training-berlin/')
    cy.get('h2').contains('Berlin - Germany')
    cy.visit('/react-redux-training-barcelona/')
    cy.get('h2').contains('Barcelona - Spain')
    cy.visit('/react-redux-training-amsterdam/')
    cy.get('h2').contains('Amsterdam - Holland')
    cy.visit('/react-redux-graphql-bootcamp-nyc/')
    cy.get('h2').contains('NYC - USA')
    cy.visit('/react-redux-graphql-bootcamp-austin/')
    cy.get('h2').contains('Austin - USA')
  })
})
